# Generated by Django 6.0.2 on 2026-03-07 06:15

import apps.api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, default=apps.api.models.generate_api_key, max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable label for this key.', max_length=200)),
                ('owner_email', models.EmailField(help_text='Contact email for the key holder.', max_length=254)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('researcher', 'Researcher'), ('institutional', 'Institutional'), ('internal', 'Internal')], db_index=True, default='free', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('requests_per_hour', models.PositiveIntegerField(default=100, help_text='Rate limit ceiling per rolling hour.')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('can_import', models.BooleanField(default=False)),
                ('can_webhook', models.BooleanField(default=False)),
                ('can_sessions', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_time_ms', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api.apikey')),
            ],
            options={
                'indexes': [models.Index(fields=['api_key', 'timestamp'], name='idx_usage_key_time'), models.Index(fields=['endpoint', 'timestamp'], name='idx_usage_endpoint_time')],
            },
        ),
    ]
