# Generated by Django 6.0.2 on 2026-03-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_import_job'),
        ('research', '0003_source_search_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_alive', models.BooleanField()),
                ('redirect_url', models.URLField(blank=True, max_length=2000)),
                ('has_archive', models.BooleanField(default=False)),
                ('archive_url', models.URLField(blank=True, max_length=2000)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='research.source')),
            ],
            options={
                'get_latest_by': 'checked_at',
                'indexes': [models.Index(fields=['source', '-checked_at'], name='idx_health_source_time')],
            },
        ),
    ]
