# Generated by Django 6.0.2 on 2026-03-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_healthcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.apikey')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('api_key', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='SessionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('source', 'Source'), ('essay', 'Essay'), ('field_note', 'Field Note'), ('thread', 'Thread')], max_length=20)),
                ('node_slug', models.SlugField(max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='api.researchsession')),
            ],
            options={
                'unique_together': {('session', 'node_type', 'node_slug')},
            },
        ),
    ]
