# Generated by Django 6.0.2 on 2026-03-07 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_research_sessions'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('callback_url', models.URLField(max_length=2000)),
                ('events', models.JSONField(help_text='List of event types to subscribe to.')),
                ('secret', models.CharField(help_text='Shared secret for HMAC signature verification.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api.apikey')),
            ],
            options={
                'unique_together': {('api_key', 'callback_url')},
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api.webhooksubscription')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
