# Generated by Django 6.0.2 on 2026-02-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('date', models.DateField()),
                ('summary', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('youtube_id', models.CharField(blank=True, default='', max_length=20)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list, help_text='Array of {title, url} objects')),
                ('related', models.JSONField(blank=True, default=list)),
                ('draft', models.BooleanField(default=True)),
                ('callout', models.CharField(blank=True, default='', max_length=500)),
                ('callouts', models.JSONField(blank=True, default=list)),
                ('stage', models.CharField(choices=[('research', 'Research'), ('drafting', 'Drafting'), ('production', 'Production'), ('published', 'Published')], default='research', max_length=20)),
                ('annotations', models.JSONField(blank=True, default=list, help_text='Array of {paragraph, text} objects')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FieldNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('date', models.DateField()),
                ('body', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('excerpt', models.CharField(blank=True, default='', max_length=300)),
                ('draft', models.BooleanField(default=True)),
                ('callout', models.CharField(blank=True, default='', max_length=500)),
                ('callouts', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(blank=True, choices=[('observation', 'Observation'), ('developing', 'Developing'), ('connected', 'Connected')], default='observation', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('connected_to', models.CharField(blank=True, default='', help_text='Slug of the parent essay this note connects to', max_length=300)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NowPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated', models.DateField()),
                ('researching', models.CharField(blank=True, default='', max_length=300)),
                ('researching_context', models.TextField(blank=True, default='')),
                ('reading', models.CharField(blank=True, default='', max_length=300)),
                ('reading_context', models.TextField(blank=True, default='')),
                ('building', models.CharField(blank=True, default='', max_length=300)),
                ('building_context', models.TextField(blank=True, default='')),
                ('listening', models.CharField(blank=True, default='', max_length=300)),
                ('listening_context', models.TextField(blank=True, default='')),
                ('thinking', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Now page',
                'verbose_name_plural': 'Now page',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('organization', models.CharField(blank=True, default='', max_length=200)),
                ('urls', models.JSONField(blank=True, default=list, help_text='Array of {label, url} objects')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('callout', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note'), ('shelf', 'Shelf Entry'), ('project', 'Project'), ('now', 'Now Page')], max_length=20)),
                ('content_slug', models.CharField(max_length=300)),
                ('content_title', models.CharField(max_length=300)),
                ('commit_sha', models.CharField(blank=True, default='', max_length=40)),
                ('commit_url', models.URLField(blank=True, default='')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShelfEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('creator', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('book', 'Book'), ('video', 'Video'), ('podcast', 'Podcast'), ('article', 'Article'), ('tool', 'Tool'), ('album', 'Album'), ('other', 'Other')], max_length=20)),
                ('annotation', models.TextField()),
                ('url', models.URLField(blank=True, default='')),
                ('date', models.DateField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('connected_essay', models.CharField(blank=True, default='', help_text='Essay slug this source relates to', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'shelf entries',
                'ordering': ['-date'],
            },
        ),
    ]
