# Generated by Django 6.0.2 on 2026-02-28 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_designtokenset_navitem_pagecomposition_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishlog',
            name='content_type',
            field=models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note'), ('shelf', 'Shelf Entry'), ('project', 'Project'), ('toolkit', 'Toolkit Entry'), ('now', 'Now Page'), ('video', 'Video'), ('site_config', 'Site Config')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title_template',
            field=models.CharField(blank=True, default='%s | travisgilbert.me', max_length=200),
        ),
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('short_title', models.CharField(blank=True, default='', help_text='Short title for TickTick tasks and dashboards', max_length=60)),
                ('phase', models.CharField(choices=[('research', 'P0: Topic Research'), ('scripting', 'P1: Script Lock'), ('voiceover', 'P2: Voiceover Record'), ('filming', 'P3: On-Camera Filming'), ('assembly', 'P4: Assembly Edit'), ('polish', 'P5: Graphics and Polish'), ('metadata', 'P6: Export and Metadata'), ('publish', 'P7: Publish'), ('published', 'Published')], default='research', max_length=20)),
                ('phase_locked_through', models.CharField(blank=True, choices=[('research', 'P0: Topic Research'), ('scripting', 'P1: Script Lock'), ('voiceover', 'P2: Voiceover Record'), ('filming', 'P3: On-Camera Filming'), ('assembly', 'P4: Assembly Edit'), ('polish', 'P5: Graphics and Polish'), ('metadata', 'P6: Export and Metadata'), ('publish', 'P7: Publish'), ('published', 'Published')], default='', help_text='Highest phase that is permanently locked (completed)', max_length=20)),
                ('draft', models.BooleanField(default=True)),
                ('thesis', models.TextField(blank=True, default='', help_text='One-sentence thesis. Often shared with linked essay.')),
                ('sources', models.JSONField(blank=True, default=list, help_text='Array of {title, url, type, role} objects')),
                ('research_notes', models.TextField(blank=True, default='', help_text='Free-form research notes (Markdown)')),
                ('script_body', models.TextField(blank=True, default='', help_text='Full script in Markdown with [VO], [ON-CAMERA], [B-ROLL], [GRAPHIC] tags')),
                ('script_word_count', models.IntegerField(default=0)),
                ('script_estimated_duration', models.CharField(blank=True, default='', help_text='Estimated video duration based on ~150 words/min VO pace', max_length=20)),
                ('youtube_title', models.CharField(blank=True, default='', max_length=100)),
                ('youtube_description', models.TextField(blank=True, default='')),
                ('youtube_tags', models.JSONField(blank=True, default=list)),
                ('youtube_category', models.CharField(blank=True, default='Education', max_length=50)),
                ('youtube_chapters', models.JSONField(blank=True, default=list, help_text='Array of {timecode, label} objects')),
                ('youtube_thumbnail_path', models.CharField(blank=True, default='', max_length=500)),
                ('youtube_id', models.CharField(blank=True, default='', help_text='YouTube video ID after upload', max_length=20)),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ticktick_task_id', models.CharField(blank=True, default='', help_text='TickTick task ID for the active phase', max_length=30)),
                ('ulysses_sheet_id', models.CharField(blank=True, default='', max_length=50)),
                ('descript_project_id', models.CharField(blank=True, default='', max_length=50)),
                ('resolve_project_name', models.CharField(blank=True, default='', max_length=200)),
                ('composition', models.JSONField(blank=True, default=dict, help_text='Per-instance visual overrides')),
                ('linked_essays', models.ManyToManyField(blank=True, help_text='Essays that share research or content with this video', related_name='video_projects', to='content.essay')),
                ('linked_field_notes', models.ManyToManyField(blank=True, help_text="Field notes connected to this video's research", related_name='video_projects', to='content.fieldnote')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('research', 'P0: Topic Research'), ('scripting', 'P1: Script Lock'), ('voiceover', 'P2: Voiceover Record'), ('filming', 'P3: On-Camera Filming'), ('assembly', 'P4: Assembly Edit'), ('polish', 'P5: Graphics and Polish'), ('metadata', 'P6: Export and Metadata'), ('publish', 'P7: Publish'), ('published', 'Published')], max_length=20)),
                ('deliverable_type', models.CharField(choices=[('research_notes', 'Research Notes'), ('script_pdf', 'Locked Script PDF'), ('script_markdown', 'Script Markdown Export'), ('vo_audio', 'VO Audio'), ('vo_transcript', 'VO Marked-Up Transcript'), ('footage', 'Camera Footage'), ('rough_cut', 'Rough Cut'), ('final_cut', 'Final Cut'), ('thumbnail', 'Thumbnail'), ('rendered_video', 'Rendered Video'), ('youtube_metadata', 'YouTube Metadata')], max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('approved', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='content.videoproject')),
            ],
            options={
                'ordering': ['phase', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('research', 'P0: Topic Research'), ('scripting', 'P1: Script Lock'), ('voiceover', 'P2: Voiceover Record'), ('filming', 'P3: On-Camera Filming'), ('assembly', 'P4: Assembly Edit'), ('polish', 'P5: Graphics and Polish'), ('metadata', 'P6: Export and Metadata'), ('publish', 'P7: Publish'), ('published', 'Published')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='', help_text='Brief description of what was accomplished this session')),
                ('subtasks_completed', models.JSONField(blank=True, default=list, help_text='Array of subtask titles completed')),
                ('next_action', models.TextField(blank=True, default='', help_text='The single next action identified at end of session')),
                ('next_tool', models.CharField(blank=True, default='', help_text='Which app/tool the next action requires (Ulysses, Descript, etc.)', max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='content.videoproject')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('scene_type', models.CharField(choices=[('vo', 'Voiceover'), ('on_camera', 'On-Camera'), ('broll', 'B-Roll'), ('graphic', 'Graphic/Animation'), ('mixed', 'Mixed')], default='vo', max_length=12)),
                ('script_text', models.TextField(blank=True, default='')),
                ('word_count', models.IntegerField(default=0)),
                ('estimated_seconds', models.IntegerField(default=0, help_text='Estimated duration in seconds (auto from word count at ~150 wpm)')),
                ('script_locked', models.BooleanField(default=False)),
                ('vo_recorded', models.BooleanField(default=False)),
                ('filmed', models.BooleanField(default=False)),
                ('assembled', models.BooleanField(default=False)),
                ('polished', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='content.videoproject')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('video', 'order')},
            },
        ),
    ]
