# Generated by Django 6.0.2 on 2026-03-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_publishlog_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='connected_types',
            field=models.JSONField(blank=True, default=list, help_text='Content types this essay connects to'),
        ),
        migrations.AddField(
            model_name='essay',
            name='connection_notes',
            field=models.TextField(blank=True, default='', help_text='Notes on how this essay relates to other content'),
        ),
        migrations.AddField(
            model_name='essay',
            name='research_notes',
            field=models.TextField(blank=True, default='', help_text='Bullet-point research process notes (one per line)'),
        ),
        migrations.AddField(
            model_name='essay',
            name='research_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='source_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='source_summary',
            field=models.CharField(blank=True, default='', help_text='Human-readable summary of source types', max_length=255),
        ),
        migrations.AddField(
            model_name='essay',
            name='thesis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
