# Generated by Django 6.0.2 on 2026-03-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_essay_connected_types_essay_connection_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='connection_notes',
            field=models.JSONField(blank=True, default=list, help_text='Array of {slug, note} objects explaining connections'),
        ),
    ]
