# Generated by Django 6.0.2 on 2026-03-03 02:58

from django.db import migrations, models


def convert_connection_notes_to_json(apps, schema_editor):
    """Convert empty string connection_notes values to empty JSON arrays.

    PostgreSQL cannot cast '' to jsonb. This data migration sets all
    non-JSON values to '[]' before the field type change.
    """
    Essay = apps.get_model('content', 'Essay')
    Essay.objects.filter(connection_notes='').update(connection_notes='[]')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_essay_connected_types_essay_connection_notes_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convert_connection_notes_to_json,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='essay',
            name='connection_notes',
            field=models.JSONField(blank=True, default=list, help_text='Array of {slug, note} objects explaining connections'),
        ),
    ]
