# Generated by Django 6.0.2 on 2026-03-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_essay_connection_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=30)),
                ('content_slug', models.SlugField(max_length=300)),
                ('text', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('ticktick_task_id', models.CharField(blank=True, default='', help_text='TickTick task ID if synced', max_length=100)),
                ('ticktick_project_id', models.CharField(blank=True, default='', help_text='TickTick project ID if synced', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=30)),
                ('content_slug', models.SlugField(max_length=300)),
                ('text', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='videoproject',
            name='evidence_board',
            field=models.JSONField(blank=True, default=list, help_text='Array of {clue, source, confidence, nextAction, visual} objects'),
        ),
    ]
