# Generated by Django 6.0.2 on 2026-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contenttask_stashitem_videoproject_evidence_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(help_text='Content type of the document containing the mention', max_length=30)),
                ('source_slug', models.SlugField(help_text='Slug of the document containing the mention', max_length=300)),
                ('target_type', models.CharField(help_text='Content type of the mentioned item', max_length=30)),
                ('target_slug', models.SlugField(help_text='Slug of the mentioned item', max_length=300)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source_type', 'source_slug', 'target_type', 'target_slug')},
            },
        ),
    ]
