# Generated by Django 6.0.2 on 2026-03-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_editormention'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(help_text='Content type (essay, field-note, video, etc.)', max_length=30)),
                ('content_slug', models.SlugField(help_text='Slug of the content item', max_length=300)),
                ('revision_number', models.PositiveIntegerField(help_text='Sequential revision number within this content item')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', help_text="Optional human label (e.g. 'before restructure')", max_length=100)),
                ('source', models.CharField(choices=[('autosave', 'Autosave'), ('manual', 'Manual Save'), ('stage', 'Stage Change'), ('restore', 'Restore Checkpoint')], default='manual', max_length=20)),
            ],
            options={
                'ordering': ['-revision_number'],
                'indexes': [models.Index(fields=['content_type', 'content_slug', '-revision_number'], name='idx_revision_lookup')],
                'unique_together': {('content_type', 'content_slug', 'revision_number')},
            },
        ),
    ]
