# Generated by Django 6.0.2 on 2026-04-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="essay",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
