# Generated by Django 6.0.2 on 2026-02-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2000)),
                ('og_title', models.CharField(blank=True, default='', max_length=500)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.URLField(blank=True, default='', max_length=2000)),
                ('og_site_name', models.CharField(blank=True, default='', max_length=300)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], default='pending', max_length=10)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_source_slug', models.SlugField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuggestedConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=20)),
                ('content_slug', models.SlugField(max_length=300)),
                ('content_title', models.CharField(blank=True, default='', max_length=500)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('accepted', models.BooleanField(null=True)),
                ('raw_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='intake.rawsource')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
