# Generated by Django 6.0.2 on 2026-03-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_backfill_phase_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawsource',
            name='extracted_content',
            field=models.TextField(blank=True, default='', help_text='Readable body text extracted from the page.'),
        ),
    ]
