/**
 * DataVizRenderer: Vega-Lite JSON spec -> offscreen stippling canvas.
 *
 * When the backend produces a Vega-Lite spec (bar chart, scatter plot,
 * heatmap), this renderer embeds it into an offscreen canvas so the
 * stippling engine can convert it into dot positions. The dots forming
 * into a bar chart is a fundamentally different experience from a
 * static SVG chart appearing.
 *
 * The ID map is generated by partitioning the rendered area into
 * semantic regions: each bar, each cluster, each intensity band.
 * Phase templates vary by chart type.
 */

import type { OffscreenRenderResult, IdEntry } from './types';
import {
  createCanvasPair,
  indexToHex,
  OFFSCREEN_SIZE,
  leftToRightPhaseTemplate,
  centerOutwardPhaseTemplate,
  uniformPhaseTemplate,
} from './types';

type ChartType = 'bar' | 'scatter' | 'line' | 'heatmap' | 'unknown';

/**
 * Infer chart type from Vega-Lite spec.
 */
function inferChartType(spec: Record<string, unknown>): ChartType {
  const mark = spec.mark;
  const markType = typeof mark === 'string' ? mark : (mark as Record<string, unknown>)?.type;

  switch (markType) {
    case 'bar': return 'bar';
    case 'point':
    case 'circle': return 'scatter';
    case 'line':
    case 'area': return 'line';
    case 'rect': return 'heatmap';
    default: return 'unknown';
  }
}

/**
 * Render a Vega-Lite spec to an offscreen canvas for stippling.
 *
 * Uses dynamic import of vega-embed to avoid SSR issues. If vega-embed
 * is unavailable, falls back to a simple placeholder rectangle.
 *
 * @param vegaSpec - Vega-Lite JSON specification
 * @param datasetLabels - Optional labels for semantic regions (bar names, cluster IDs)
 */
export async function renderDataViz(
  vegaSpec: Record<string, unknown>,
  datasetLabels?: string[],
): Promise<OffscreenRenderResult> {
  const { visual, visualCtx, idMap, idCtx } = createCanvasPair();
  const S = OFFSCREEN_SIZE;
  const idLegend = new Map<string, IdEntry>();
  const chartType = inferChartType(vegaSpec);

  try {
    // Render Vega-Lite to a temporary DOM element, then capture to canvas
    const vegaEmbed = await import('vega-embed');

    // Create a temporary hidden container
    const container = document.createElement('div');
    container.style.position = 'fixed';
    container.style.left = '-9999px';
    container.style.top = '-9999px';
    container.style.width = `${S}px`;
    container.style.height = `${S}px`;
    document.body.appendChild(container);

    try {
      // Override spec to be high-contrast: white on black, no grid
      const stipplingSpec = {
        ...vegaSpec,
        width: S - 40,
        height: S - 40,
        padding: 20,
        background: '#000000',
        config: {
          axis: { grid: false, labels: false, ticks: false, domain: false },
          legend: { disable: true },
          title: { color: '#000000' },
          view: { stroke: null },
          mark: { color: '#ffffff' },
          bar: { color: '#ffffff' },
          point: { color: '#ffffff', filled: true },
          line: { color: '#ffffff', strokeWidth: 4 },
          area: { color: '#ffffff' },
          rect: { color: '#ffffff' },
        },
      };

      const result = await vegaEmbed.default(container, stipplingSpec as never, {
        actions: false,
        renderer: 'canvas',
      });

      // Capture the Vega canvas
      const vegaCanvas = container.querySelector('canvas');
      if (vegaCanvas) {
        visualCtx.drawImage(vegaCanvas, 0, 0, S, S);
      }

      result.finalize();
    } finally {
      document.body.removeChild(container);
    }
  } catch {
    // Fallback: draw a simple placeholder rectangle
    visualCtx.fillStyle = '#ffffff';
    const padX = S * 0.15;
    const padY = S * 0.15;
    visualCtx.fillRect(padX, padY, S - padX * 2, S - padY * 2);
  }

  // Generate ID map by partitioning into regions
  // For bar charts: vertical strips. For scatter: quadrants. For heatmap: grid.
  const regionCount = datasetLabels?.length ?? 4;

  if (chartType === 'bar') {
    const padX = S * 0.15;
    const usableW = S - padX * 2;
    const barWidth = usableW / regionCount;

    for (let i = 0; i < regionCount; i++) {
      const hex = indexToHex(i);
      idCtx.fillStyle = hex;
      idCtx.fillRect(padX + i * barWidth, S * 0.15, barWidth, S * 0.7);
      idLegend.set(hex, { nodeId: datasetLabels?.[i] ?? `bar-${i}` });
    }
  } else if (chartType === 'scatter') {
    // Quadrant-based regions
    const half = S / 2;
    const quadrants = [
      { x: 0, y: 0, label: 'top-left' },
      { x: half, y: 0, label: 'top-right' },
      { x: 0, y: half, label: 'bottom-left' },
      { x: half, y: half, label: 'bottom-right' },
    ];
    for (let i = 0; i < quadrants.length; i++) {
      const hex = indexToHex(i);
      idCtx.fillStyle = hex;
      idCtx.fillRect(quadrants[i].x, quadrants[i].y, half, half);
      idLegend.set(hex, { nodeId: datasetLabels?.[i] ?? quadrants[i].label });
    }
  } else {
    // Grid partition for heatmaps and unknowns
    const gridSize = 4;
    const cellW = S / gridSize;
    const cellH = S / gridSize;
    let idx = 0;
    for (let row = 0; row < gridSize; row++) {
      for (let col = 0; col < gridSize; col++) {
        const hex = indexToHex(idx);
        idCtx.fillStyle = hex;
        idCtx.fillRect(col * cellW, row * cellH, cellW, cellH);
        idLegend.set(hex, { nodeId: datasetLabels?.[idx] ?? `cell-${row}-${col}` });
        idx++;
      }
    }
  }

  // Phase template by chart type
  let phaseTemplate: number[][];
  switch (chartType) {
    case 'bar':
    case 'line':
      phaseTemplate = leftToRightPhaseTemplate(8, Math.min(5, regionCount));
      break;
    case 'scatter':
      phaseTemplate = centerOutwardPhaseTemplate(8, 3);
      break;
    case 'heatmap':
      phaseTemplate = centerOutwardPhaseTemplate(8, 4);
      break;
    default:
      phaseTemplate = uniformPhaseTemplate(8);
  }

  return { visual, idMap, idLegend, phaseTemplate };
}
