# Generated by Django 6.0.2 on 2026-03-02 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note'), ('shelf', 'Shelf Entry'), ('project', 'Project'), ('toolkit', 'Toolkit Entry'), ('video', 'Video Project')], max_length=20)),
                ('content_slug', models.SlugField(max_length=255)),
                ('text', models.TextField(help_text='Markdown research note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'content_slug'], name='editor_rn_ct_slug_idx')],
            },
        ),
    ]
