# Generated by Django 6.0.2 on 2026-03-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_connectionsuggestion_sourcesuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('nodes_created', models.JSONField(default=list, help_text='List of {id, title, node_type} dicts for nodes created this day.')),
                ('nodes_updated', models.JSONField(default=list, help_text='List of {id, title, action} dicts for nodes modified this day.')),
                ('edges_created', models.JSONField(default=list, help_text='List of {id, from_title, to_title, reason} dicts.')),
                ('entities_resolved', models.JSONField(default=list, help_text='List of {text, entity_type, resolved_to} dicts.')),
                ('summary', models.TextField(blank=True, help_text='Auto-generated natural language summary of the day.')),
            ],
            options={
                'verbose_name': 'daily log',
                'verbose_name_plural': 'daily logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='note-pencil', help_text='SketchIcon name for this type.', max_length=50)),
                ('color', models.CharField(default='#2D5F6B', help_text='Brand hex color for this type in the UI.', max_length=7)),
                ('schema', models.JSONField(blank=True, default=dict, help_text='JSON schema defining expected properties for this type. Example for Person: {"fields": ["born", "died", "role", "org"]}')),
                ('is_built_in', models.BooleanField(default=False, help_text='Built-in types cannot be deleted.')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Optional. Auto-generated from body or OG metadata if blank.', max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, help_text='Freeform markdown. Notes, quotes, observations, hunches.')),
                ('url', models.URLField(blank=True, help_text='Optional. Source URL if this node has one.', max_length=2000)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Type-specific properties. Person: {born, role, org}. Source: {author, publication, date_published}. Hunch: {confidence, revisit_date}.')),
                ('og_title', models.CharField(blank=True, max_length=500)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True, max_length=2000)),
                ('og_site_name', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('inbox', 'Inbox'), ('active', 'Active'), ('archive', 'Archive')], db_index=True, default='inbox', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('notebooks', models.JSONField(blank=True, default=list, help_text='Named notebook slugs this node belongs to.')),
                ('related_essays', models.JSONField(blank=True, default=list)),
                ('related_field_notes', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('capture_method', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('browser_ext', 'Browser Extension'), ('auto', 'Auto-extracted')], default='manual', max_length=20)),
                ('promoted_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_nodes', to='research.source')),
                ('node_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='nodes', to='notebook.nodetype')),
            ],
            options={
                'ordering': ['-is_pinned', '-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#2D5F6B', max_length=7)),
                ('icon', models.CharField(default='book-open', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('target_essay_slug', models.SlugField(blank=True, max_length=300)),
                ('target_video_slug', models.SlugField(blank=True, max_length=300)),
                ('nodes', models.ManyToManyField(blank=True, related_name='notebook_memberships', to='notebook.knowledgenode')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResolvedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='The entity text as found in the source, e.g. "Richard Hamming".', max_length=300)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORG', 'Organization'), ('GPE', 'Place (geo-political)'), ('LOC', 'Location'), ('DATE', 'Date'), ('EVENT', 'Event'), ('WORK_OF_ART', 'Work of Art'), ('CONCEPT', 'Concept')], db_index=True, max_length=20)),
                ('normalized_text', models.CharField(blank=True, help_text='Cleaned/canonical form, e.g. "richard hamming" for matching.', max_length=300)),
                ('resolved_node', models.ForeignKey(blank=True, help_text='The KnowledgeNode this entity resolves to (if one exists).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_mentions', to='notebook.knowledgenode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_entities', to='notebook.knowledgenode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edge_type', models.CharField(choices=[('mentions', 'Mentions'), ('shared_entity', 'Shared Entity'), ('shared_topic', 'Shared Topic'), ('sequence', 'Sequence'), ('supports', 'Supports'), ('contradicts', 'Contradicts'), ('inspires', 'Inspires'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Plain English explanation of why this connection exists. Example: "Both notes discuss suburban zoning patterns from the 1950s."')),
                ('strength', models.FloatField(default=0.5, help_text='Connection strength from 0.0 (weak) to 1.0 (strong). Used for edge thickness in D3 visualizations.')),
                ('is_auto', models.BooleanField(default=False, help_text='True if created by the connection engine, False if manual.')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='notebook.knowledgenode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='notebook.knowledgenode')),
            ],
            options={
                'ordering': ['-strength', '-created_at'],
                'indexes': [models.Index(fields=['from_node', 'edge_type'], name='idx_edge_from_type'), models.Index(fields=['to_node', 'edge_type'], name='idx_edge_to_type')],
                'constraints': [models.UniqueConstraint(fields=('from_node', 'to_node', 'edge_type'), name='unique_edge_per_type')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['status', '-captured_at'], name='idx_node_status_date'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['-is_pinned', '-captured_at'], name='idx_node_pinned_date'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['node_type', '-captured_at'], name='idx_node_type_date'),
        ),
        migrations.AddIndex(
            model_name='resolvedentity',
            index=models.Index(fields=['normalized_text', 'entity_type'], name='idx_entity_norm'),
        ),
        migrations.AddIndex(
            model_name='resolvedentity',
            index=models.Index(fields=['source_node'], name='idx_entity_source'),
        ),
    ]
