# Generated by Django 6.0.2 on 2026-03-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_connectionsuggestion_sourcesuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('recurring_date', 'Recurring Date'), ('relationship', 'Relationship'), ('location', 'Location'), ('file', 'File'), ('url', 'URL'), ('status', 'Status'), ('number', 'Number'), ('tag', 'Tag'), ('code', 'Code')], max_length=20)),
                ('triggers_node', models.BooleanField(default=False, help_text='When True, creating or updating a Component of this type auto-creates a Node on the Timeline.')),
                ('schema', models.JSONField(blank=True, default=dict, help_text='Validation schema for the value field.')),
                ('is_built_in', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('objects_created', models.JSONField(default=list, help_text='List of {id, title, object_type} dicts for objects created this day.')),
                ('objects_updated', models.JSONField(default=list, help_text='List of {id, title, action} dicts for objects modified this day.')),
                ('edges_created', models.JSONField(default=list, help_text='List of {id, from_title, to_title, reason} dicts.')),
                ('entities_resolved', models.JSONField(default=list, help_text='List of {text, entity_type, resolved_to} dicts.')),
                ('summary', models.TextField(blank=True, help_text='Auto-generated natural language summary of the day.')),
            ],
            options={
                'verbose_name': 'daily log',
                'verbose_name_plural': 'daily logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('config', models.JSONField(default=dict, help_text='Pane tree structure defining the layout.')),
                ('is_preset', models.BooleanField(default=False, help_text='Built-in presets cannot be deleted.')),
            ],
            options={
                'ordering': ['-is_preset', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#2D5F6B', max_length=7)),
                ('icon', models.CharField(default='book-open', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('target_essay_slug', models.SlugField(blank=True, max_length=300)),
                ('target_video_slug', models.SlugField(blank=True, max_length=300)),
                ('engine_config', models.JSONField(blank=True, default=dict, help_text='Connection engine overrides. Example: {"engines": ["spacy", "tfidf"], "topic_threshold": 0.25}')),
                ('available_types', models.JSONField(blank=True, default=list, help_text='List of ObjectType slugs available in this notebook context.')),
                ('default_layout', models.JSONField(blank=True, default=dict, help_text='Default pane configuration for this notebook.')),
                ('theme', models.JSONField(blank=True, default=dict, help_text='Visual theme overrides (colors, fonts, etc.).')),
                ('context_behavior', models.JSONField(blank=True, default=dict, help_text='Context-specific behavior rules.')),
                ('default_project_mode', models.CharField(choices=[('knowledge', 'Knowledge'), ('manage', 'Manage')], default='knowledge', help_text='Default mode for new Projects in this Notebook.', max_length=20)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(default='note-pencil', help_text='SketchIcon name for this type.', max_length=50)),
                ('color', models.CharField(default='#2D5F6B', help_text='Brand hex color for this type in the UI.', max_length=7)),
                ('schema', models.JSONField(blank=True, default=dict, help_text='JSON schema defining expected properties for this type. Example for Person: {"fields": ["born", "died", "role", "org"]}')),
                ('default_components', models.JSONField(blank=True, default=list, help_text='List of ComponentType slugs to auto-attach when creating Objects of this type. Example: ["url", "author", "date"]')),
                ('is_built_in', models.BooleanField(default=False, help_text='Built-in types cannot be deleted.')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha_hash', models.CharField(editable=False, help_text='SHA-256 fingerprint for provenance tracking.', max_length=40, unique=True)),
                ('title', models.CharField(blank=True, help_text='Optional. Auto-generated from body or OG metadata if blank.', max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, help_text='Freeform markdown. Notes, quotes, observations, hunches.')),
                ('url', models.URLField(blank=True, help_text='Optional. Source URL if this object has one.', max_length=2000)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Type-specific key/value properties.')),
                ('og_title', models.CharField(blank=True, max_length=500)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True, max_length=2000)),
                ('og_site_name', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archive', 'Archive')], db_index=True, default='active', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('related_essays', models.JSONField(blank=True, default=list)),
                ('related_field_notes', models.JSONField(blank=True, default=list)),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('capture_method', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('browser_ext', 'Browser Extension'), ('auto', 'Auto-extracted')], default='manual', max_length=20)),
                ('notebook', models.ForeignKey(blank=True, help_text='Primary notebook this object belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notebook_objects', to='notebook.notebook')),
                ('promoted_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_objects', to='research.source')),
                ('object_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='typed_objects', to='notebook.objecttype')),
            ],
            options={
                'ordering': ['-is_pinned', '-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Human label: "birthday", "author", "hometown".', max_length=200)),
                ('value', models.JSONField(blank=True, default=dict, help_text='Flexible storage. Shape depends on component_type.data_type.')),
                ('sort_order', models.IntegerField(default=0)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='notebook.componenttype')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='notebook.object')),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sha_hash', models.CharField(editable=False, max_length=40, unique=True)),
                ('mode', models.CharField(choices=[('knowledge', 'Knowledge'), ('manage', 'Manage')], default='knowledge', max_length=20)),
                ('is_template', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('settings_override', models.JSONField(blank=True, default=dict, help_text='Per-project engine/UI settings that override notebook defaults.')),
                ('description', models.TextField(blank=True)),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='notebook.notebook')),
                ('template_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_projects', to='notebook.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_objects', to='notebook.project'),
        ),
        migrations.CreateModel(
            name='ResolvedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(help_text='The entity text as found in the source, e.g. "Richard Hamming".', max_length=300)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORG', 'Organization'), ('GPE', 'Place (geo-political)'), ('LOC', 'Location'), ('DATE', 'Date'), ('EVENT', 'Event'), ('WORK_OF_ART', 'Work of Art'), ('CONCEPT', 'Concept')], db_index=True, max_length=20)),
                ('normalized_text', models.CharField(blank=True, help_text='Cleaned/canonical form, e.g. "richard hamming" for matching.', max_length=300)),
                ('resolved_object', models.ForeignKey(blank=True, help_text='The Object this entity resolves to (if one exists).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_mentions', to='notebook.object')),
                ('source_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_entities', to='notebook.object')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_master', models.BooleanField(default=False, help_text='There must be exactly one master Timeline.')),
                ('filter_config', models.JSONField(blank=True, default=dict, help_text='Filter rules for sub-timelines (node_type, object_type, etc.).')),
                ('engine_config', models.JSONField(blank=True, default=dict, help_text='Engine config override for this timeline context.')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='notebook.notebook')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='notebook.project')),
            ],
            options={
                'ordering': ['-is_master', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sha_hash', models.CharField(editable=False, max_length=40, unique=True)),
                ('node_type', models.CharField(choices=[('creation', 'Creation'), ('deletion', 'Deletion'), ('modification', 'Modification'), ('connection', 'Connection'), ('reminder_set', 'Reminder Set'), ('reminder_fired', 'Reminder Fired'), ('reminder_dismissed', 'Reminder Dismissed'), ('project_completed', 'Project Completed'), ('project_created', 'Project Created'), ('recurring_date', 'Recurring Date'), ('capture', 'Capture'), ('retrospective', 'Retrospective'), ('status_change', 'Status Change'), ('component_trigger', 'Component Trigger')], db_index=True, max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('retrospective_notes', models.JSONField(blank=True, default=list, help_text='List of {text, sha, created_at} dicts added after the fact.')),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('component_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='notebook.component')),
                ('object_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='notebook.object')),
                ('project_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='notebook.project')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='notebook.timeline')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edge_type', models.CharField(choices=[('mentions', 'Mentions'), ('shared_entity', 'Shared Entity'), ('shared_topic', 'Shared Topic'), ('similarity', 'Similarity'), ('sequence', 'Sequence'), ('supports', 'Supports'), ('contradicts', 'Contradicts'), ('inspires', 'Inspires'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Plain English explanation of why this connection exists. Example: "Both notes discuss suburban zoning patterns from the 1950s."')),
                ('strength', models.FloatField(default=0.5, help_text='Connection strength from 0.0 (weak) to 1.0 (strong). Used for edge thickness in D3 visualizations.')),
                ('is_auto', models.BooleanField(default=False, help_text='True if created by the connection engine, False if manual.')),
                ('engine', models.CharField(blank=True, help_text='Which engine found this: spacy, js, tfidf, semantic, manual.', max_length=20)),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='notebook.object')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='notebook.object')),
            ],
            options={
                'ordering': ['-strength', '-created_at'],
                'indexes': [models.Index(fields=['from_object', 'edge_type'], name='idx_edge_from_type'), models.Index(fields=['to_object', 'edge_type'], name='idx_edge_to_type')],
                'constraints': [models.UniqueConstraint(fields=('from_object', 'to_object', 'edge_type'), name='unique_edge_per_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('object', 'component_type', 'key'), name='unique_component_per_object'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['status', '-captured_at'], name='idx_obj_status_date'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['-is_pinned', '-captured_at'], name='idx_obj_pinned_date'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['object_type', '-captured_at'], name='idx_obj_type_date'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['notebook', '-captured_at'], name='idx_obj_notebook_date'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['project', '-captured_at'], name='idx_obj_project_date'),
        ),
        migrations.AddIndex(
            model_name='resolvedentity',
            index=models.Index(fields=['normalized_text', 'entity_type'], name='idx_entity_norm'),
        ),
        migrations.AddIndex(
            model_name='resolvedentity',
            index=models.Index(fields=['source_object'], name='idx_entity_source'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type', '-occurred_at'], name='idx_node_type_occurred'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['timeline', '-occurred_at'], name='idx_node_timeline_occurred'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['object_ref', '-occurred_at'], name='idx_node_objref_occurred'),
        ),
    ]
