# Generated by Django 6.0.2 on 2026-03-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft-delete flag. Deleted Objects stay in the DB for Timeline integrity but are excluded from all API responses and future connection discovery.'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_sha',
            field=models.CharField(blank=True, default='', help_text='SHA of the parent Project this was forked from (empty if original).', max_length=40),
        ),
        migrations.AlterField(
            model_name='edge',
            name='edge_type',
            field=models.CharField(choices=[('mentions', 'Mentions'), ('shared_entity', 'Shared Entity'), ('shared_topic', 'Shared Topic'), ('similarity', 'Similarity'), ('sequence', 'Sequence'), ('supports', 'Supports'), ('contradicts', 'Contradicts'), ('inspires', 'Inspires'), ('related', 'Related'), ('manual', 'Manual')], db_index=True, default='manual', max_length=30),
        ),
    ]
