# Generated by Django 6.0.2 on 2026-03-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_add_soft_delete_related_edge_parent_sha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttype',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('date', 'Date'), ('recurring_date', 'Recurring Date'), ('relationship', 'Relationship'), ('location', 'Location'), ('file', 'File'), ('url', 'URL'), ('status', 'Status'), ('number', 'Number'), ('tag', 'Tag'), ('code', 'Code'), ('history', 'History')], max_length=20),
        ),
    ]
