# Generated by Django 6.0.2 on 2026-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_add_history_data_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('from_object', models.F('to_object')), _negated=True), name='no_self_edges'),
        ),
    ]
