# Generated by Django 6.0.2 on 2026-03-11 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0005_postgres_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='edge_type',
            field=models.CharField(choices=[('mentions', 'Mentions'), ('shared_entity', 'Shared Entity'), ('shared_topic', 'Shared Topic'), ('similarity', 'Similarity'), ('sequence', 'Sequence'), ('supports', 'Supports'), ('contradicts', 'Contradicts'), ('inspires', 'Inspires'), ('related', 'Related'), ('manual', 'Manual'), ('semantic', 'Semantic'), ('structural', 'Structural (KGE)'), ('causal', 'Causal Influence'), ('entailment', 'Entailment')], db_index=True, default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='edge',
            name='engine',
            field=models.CharField(blank=True, help_text='Which engine found this: spacy, graph_ner, bm25, sbert, sbert_faiss, nli, kge, kge_temporal, causal, manual.', max_length=30),
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('label_tags', models.JSONField(blank=True, default=list, help_text='Auto-generated label from top entity/topic tags.')),
                ('modularity_score', models.FloatField(default=0.0, help_text='Cluster quality metric from community detection.')),
                ('member_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, help_text='LLM-generated summary of cluster themes.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='notebook.notebook')),
            ],
            options={
                'ordering': ['-member_count'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='notebook.cluster'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='A single falsifiable assertion extracted from the Object.')),
                ('claim_index', models.IntegerField(default=0, help_text='Position of this claim within the source Object.')),
                ('embedding', models.BinaryField(blank=True, help_text='SBERT embedding as bytes (for FAISS indexing).', null=True)),
                ('source_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='notebook.object')),
            ],
            options={
                'ordering': ['source_object', 'claim_index'],
                'indexes': [models.Index(fields=['source_object'], name='idx_claim_source')],
            },
        ),
    ]
