# Generated by Django 5.2.6 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notebook', '0006_engine_upgrade_batch3'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='is_auto_generated',
            field=models.BooleanField(
                default=False,
                help_text='True when created by self-organization loops.',
            ),
        ),
    ]
