# Generated by Django 6.0.2 on 2026-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webmention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(help_text='The URL of the page that mentions our content.', max_length=2000)),
                ('target_url', models.URLField(db_index=True, help_text='The URL on our site being mentioned.', max_length=2000)),
                ('author_name', models.CharField(blank=True, max_length=300)),
                ('author_url', models.URLField(blank=True, max_length=2000)),
                ('author_photo', models.URLField(blank=True, max_length=2000)),
                ('content', models.TextField(blank=True, help_text='Excerpt or summary extracted from the source page.')),
                ('mention_type', models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('like', 'Like'), ('repost', 'Repost'), ('bookmark', 'Bookmark')], default='mention', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Has the source URL been fetched and confirmed?')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('spam', 'Spam')], db_index=True, default='pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_mention_status_date')],
                'constraints': [models.UniqueConstraint(fields=('source_url', 'target_url'), name='unique_mention_pair')],
            },
        ),
    ]
