# Generated by Django 6.0.2 on 2026-02-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name (person or site).', max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('domain', models.CharField(help_text='Root domain (e.g. "example.com"). Used to match incoming mentions.', max_length=300, unique=True)),
                ('url', models.URLField(blank=True, help_text='Home page of the site or author profile.', max_length=2000)),
                ('description', models.TextField(blank=True, help_text='Short description of this source.')),
                ('avatar_url', models.URLField(blank=True, help_text='Avatar or logo URL for display.', max_length=2000)),
                ('trusted', models.BooleanField(db_index=True, default=False, help_text='Mentions from this source auto-verify and auto-publish.')),
            ],
            options={
                'verbose_name': 'mention source',
                'verbose_name_plural': 'mention sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(help_text='URL of the page that mentions your content.', max_length=2000)),
                ('source_title', models.CharField(blank=True, help_text='Title of the linking page.', max_length=500)),
                ('source_excerpt', models.TextField(blank=True, help_text='Relevant excerpt from the source page.')),
                ('source_author', models.CharField(blank=True, help_text='Author name extracted from the source.', max_length=300)),
                ('source_author_url', models.URLField(blank=True, help_text='Author profile URL.', max_length=2000)),
                ('source_published', models.DateTimeField(blank=True, help_text='When the source page was published.', null=True)),
                ('target_content_type', models.CharField(choices=[('essay', 'Essay'), ('field_note', 'Field Note'), ('project', 'Project'), ('toolkit', 'Toolkit'), ('shelf', 'Shelf'), ('page', 'Page'), ('other', 'Other')], db_index=True, default='essay', help_text='Type of content being mentioned.', max_length=20)),
                ('target_slug', models.SlugField(help_text='Slug of the content being mentioned.', max_length=300)),
                ('target_url', models.URLField(blank=True, help_text='Full URL of the target page (for Webmention protocol).', max_length=2000)),
                ('mention_type', models.CharField(choices=[('reply', 'Reply'), ('link', 'Link'), ('repost', 'Repost'), ('like', 'Like'), ('mention', 'Mention'), ('quote', 'Quote')], db_index=True, default='mention', max_length=20)),
                ('discovery_method', models.CharField(choices=[('webmention', 'Webmention'), ('manual', 'Manual'), ('referrer', 'Referrer'), ('search', 'Search')], db_index=True, default='webmention', max_length=20)),
                ('verified', models.BooleanField(default=False, help_text='Source URL fetched and confirmed to link to the target.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('public', models.BooleanField(db_index=True, default=False, help_text='Whether this mention appears on the public site.')),
                ('featured', models.BooleanField(default=False, help_text='Highlighted in the Conversation section.')),
                ('webmention_vouch', models.URLField(blank=True, help_text='Vouch URL for extended Webmention verification.', max_length=2000)),
                ('mention_source', models.ForeignKey(blank=True, help_text='Known source site (auto-matched by domain or set manually).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='mentions.mentionsource')),
            ],
            options={
                'verbose_name': 'mention',
                'verbose_name_plural': 'mentions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_content_type', 'target_slug'], name='idx_mention_target_lookup'), models.Index(fields=['public', '-created_at'], name='idx_mention_public_date'), models.Index(fields=['verified', '-created_at'], name='idx_mention_verified_date')],
                'constraints': [models.UniqueConstraint(fields=('source_url', 'target_slug'), name='unique_mention_per_target')],
            },
        ),
    ]
