# Generated by Django 6.0.2 on 2026-02-26 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this research thread is investigating.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], db_index=True, default='active', max_length=20)),
                ('started_date', models.DateField(blank=True, help_text='When this line of investigation began.', null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('source_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('paper', 'Academic Paper'), ('podcast', 'Podcast'), ('talk', 'Talk / Lecture'), ('video', 'Video'), ('report', 'Report'), ('dataset', 'Dataset'), ('other', 'Other')], db_index=True, default='article', max_length=20)),
                ('authors', models.JSONField(blank=True, default=list, help_text='List of author names, e.g. ["Jane Jacobs", "Robert Caro"]')),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('isbn', models.CharField(blank=True, max_length=20, verbose_name='ISBN')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('notes', models.TextField(blank=True, help_text='Personal notes, key takeaways, or why this source matters.')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization, e.g. ["urban-design", "housing"]')),
                ('cover_image_url', models.URLField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', '-created_at'], name='idx_source_type_date')],
            },
        ),
        migrations.CreateModel(
            name='ThreadEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='When this milestone occurred.')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(blank=True, help_text='Description of what happened or what was discovered.')),
                ('content_type', models.CharField(blank=True, choices=[('essay', 'Essay'), ('field-note', 'Field Note'), ('project', 'Project')], help_text='If this entry produced published content, its type.', max_length=20)),
                ('content_slug', models.SlugField(blank=True, help_text='If this entry produced published content, its slug.', max_length=300)),
                ('sources', models.ManyToManyField(blank=True, help_text='Sources relevant to this milestone.', related_name='thread_entries', to='research.source')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='research.researchthread')),
            ],
            options={
                'verbose_name_plural': 'thread entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('essay', 'Essay'), ('field-note', 'Field Note'), ('project', 'Project')], db_index=True, max_length=20)),
                ('content_slug', models.SlugField(max_length=300)),
                ('content_title', models.CharField(blank=True, help_text='Display title of the content piece (for admin convenience).', max_length=500)),
                ('context', models.TextField(blank=True, help_text='How or where this source is referenced in the content.')),
                ('paragraph_index', models.PositiveIntegerField(blank=True, help_text='1-based paragraph number where this source is cited.', null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='research.source')),
            ],
            options={
                'ordering': ['content_type', 'content_slug'],
                'indexes': [models.Index(fields=['content_type', 'content_slug'], name='idx_content_ref_lookup')],
                'constraints': [models.UniqueConstraint(fields=('source', 'content_type', 'content_slug'), name='unique_source_per_content')],
            },
        ),
    ]
