# Generated by Django 6.0.2 on 2026-03-06 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_slug', models.SlugField(max_length=300)),
                ('content_type', models.CharField(choices=[('essays', 'Essays'), ('field-notes', 'Field Notes')], max_length=20)),
                ('paragraph_index', models.PositiveIntegerField()),
                ('author_name', models.CharField(max_length=80)),
                ('body', models.TextField(max_length=600)),
                ('is_flagged', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('recaptcha_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'article_slug', 'created_at'], name='comment_article_lookup')],
            },
        ),
    ]
